Melodia\PageBundle\Entity\Page:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: url
    properties:
        url:
            - NotBlank: ~
        title:
            - NotBlank: ~
        description:
            - NotBlank: ~
        keywords:
            - NotBlank: ~

Melodia\PageBundle\Entity\PageBlock:
    properties:
        type:
            - NotBlank: ~
        json:
            - NotBlank: ~
